spring:

  # Application
  application:
    name: mobile-application-service

  # Security
  security:
    user:
      name: spring
      password: boot

  # Active Profile
  profiles:
    active: dev
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /mobile-app-ws
